services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spaye-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - spaye-network

# ✅ Définir le réseau ici si vous voulez qu'il soit créé automatiquement
networks:
  spaye-network:
    external: true