services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spaye-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - spaye-network

# ✅ Utiliser un réseau externe (déjà créé manuellement)
networks:
  spaye-network:
    external: true
